# Generated by Django 4.2.7 on 2025-08-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('time_slot', models.CharField(choices=[('morning', '🌅 Morning'), ('afternoon', '☀️ Afternoon'), ('evening', '🌆 Evening'), ('night', '🌙 Night')], max_length=20)),
                ('specific_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('alert_type', models.CharField(choices=[('tone', '🔊 Tone'), ('vibrate', '📳 Vibrate'), ('visual', '👁️ Visual')], default='tone', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['time_slot', 'specific_time'],
            },
        ),
    ]
