# Generated by Django 4.2.7 on 2025-08-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='send_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='send_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='alert_type',
            field=models.CharField(choices=[('tone', '🔊 Tone'), ('vibrate', '📳 Vibrate'), ('visual', '👁️ Visual'), ('email', '📧 Email'), ('sms', '📱 SMS'), ('all', '🔔 All (Email + SMS + App)')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time_slot',
            field=models.CharField(choices=[('morning', '🌅 Morning (6 AM - 12 PM)'), ('afternoon', '☀️ Afternoon (12 PM - 6 PM)'), ('evening', '🌆 Evening (6 PM - 9 PM)'), ('night', '🌙 Night (9 PM - 6 AM)')], max_length=20),
        ),
    ]
