# Generated by Django 4.2.7 on 2025-08-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_reminder_send_email_reminder_send_sms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date for notifications', null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date for notifications', null=True),
        ),
    ]
