# Generated by Django 4.2.7 on 2025-08-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_reminder_end_date_reminder_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='start_date',
        ),
        migrations.AddField(
            model_name='reminder',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
