# Generated by Django 4.2.7 on 2025-08-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0005_remove_reminder_end_date_remove_reminder_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
