# Generated by Django 4.2.7 on 2025-09-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0006_reminder_taken_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='send_sms',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='alert_type',
            field=models.CharField(choices=[('tone', '🔊 Tone'), ('vibrate', '📳 Vibrate'), ('visual', '👁️ Visual'), ('email', '📧 Email'), ('all', '🔔 All (Email + App)')], default='all', max_length=20),
        ),
    ]
