# Generated by Django 4.2.7 on 2025-09-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
