# Generated by Django 4.2.7 on 2025-09-06 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0004_add_email_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_pharmacy', to=settings.AUTH_USER_MODEL),
        ),
    ]
