# Generated by Django 4.2.7 on 2025-09-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_initial'),
        ('orders', '0006_alter_cart_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'medicine')},
        ),
    ]
