# Generated by Django 4.2.7 on 2025-09-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_prescription_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_email',
            field=models.EmailField(blank=True, help_text='Email for delivery notifications (optional)', max_length=254),
        ),
    ]
