# Generated by Django 4.2.7 on 2025-09-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_alter_pharmacy_owner'),
        ('orders', '0010_order_delivery_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceorder',
            name='order_type',
            field=models.CharField(choices=[('prescription', 'Prescription Order'), ('restock', 'Inventory Restock')], default='prescription', max_length=20),
        ),
        migrations.AddField(
            model_name='advanceorder',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='advanceorder',
            name='supplier_contact',
            field=models.CharField(blank=True, help_text='Supplier contact for restock orders', max_length=200),
        ),
        migrations.AddField(
            model_name='advanceorder',
            name='supplier_name',
            field=models.CharField(blank=True, help_text='Supplier name for restock orders', max_length=200),
        ),
        migrations.AlterField(
            model_name='advanceorder',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.prescription'),
        ),
    ]
