# Generated by Django 4.2.7 on 2025-09-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_advanceorder_order_type_advanceorder_pharmacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_advance_order',
            field=models.BooleanField(default=False, help_text='Whether this cart item is for an advance order'),
        ),
        migrations.AddField(
            model_name='order',
            name='advance_order_type',
            field=models.CharField(blank=True, choices=[('prescription', 'Prescription Order'), ('restock', 'Inventory Restock')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_advance_order',
            field=models.BooleanField(default=False, help_text='Whether this is an advance order'),
        ),
    ]
