# Generated by Django 4.2.7 on 2025-09-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_cartitem_is_advance_order_order_advance_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceorder',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the advance order has been verified by pharmacist'),
        ),
        migrations.AddField(
            model_name='advanceorder',
            name='verification_code',
            field=models.CharField(blank=True, help_text='Verification code for pharmacist', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the order has been verified by pharmacist'),
        ),
        migrations.AddField(
            model_name='order',
            name='verification_code',
            field=models.CharField(blank=True, help_text='Verification code for pharmacist', max_length=6, null=True),
        ),
    ]
